return {
  "mfussenegger/nvim-dap",

  config = function()
    local dap = require("dap")

    local keymap = vim.keymap
    keymap.set('n', '<F5>', function()
      dap.continue()
    end, { desc = 'DAP Continue' })
    keymap.set('n', '<F10>', function()
      dap.step_over()
    end, { desc = 'DAP Step over' })
    keymap.set('n', '<F11>', function()
      dap.step_into()
    end, { desc = 'DAP Step into' })
    keymap.set('n', '<F12>', function()
      dap.step_out()
    end, { desc = 'DAP Step out' })
    keymap.set('n', '<Leader>b', function()
      dap.toggle_breakpoint()
    end, { desc = 'DAP Toggle breakpoint' })
    keymap.set('n', '<Leader>B', function()
      dap.set_breakpoint()
    end, { desc = 'DAP Set breakpoint' })
    keymap.set('n', '<Leader>lp', function()
      dap.set_breakpoint(nil, nil, vim.fn.input('Log point message: '))
    end, { desc = 'DAP Set breakpoint extended' })
    keymap.set('n', '<Leader>dr', function()
      dap.repl.open()
    end, { desc = 'DAP Open REPL' })
    keymap.set('n', '<Leader>dl', function()
      dap.run_last()
    end, { desc = 'DAP Run last' })
    local widgets = require('dap.ui.widgets')
    keymap.set({ 'n', 'v' }, '<Leader>dh', function()
      widgets.hover()
    end, { desc = 'DAP hover widget' })
    keymap.set({ 'n', 'v' }, '<Leader>dp', function()
      widgets.preview()
    end, { desc = 'DAP preview widget' })
    keymap.set('n', '<Leader>df', function()
      widgets.centered_float(widgets.frames)
    end, { desc = 'DAP frames widget' })
    keymap.set('n', '<Leader>ds', function()
      widgets.centered_float(widgets.scopes)
    end, { desc = 'DAP scopes widget' })
  end
}
